name: ExtraStorageAddon
version: '${project.version}'
main: net.danh.extrastorageaddon.ExtraStorageAddon
api-version: 1.13
depend: [ ExtraStorage ]
authors: [ VoChiDanh ]
description: ${project.description}
